- name: (MacOS) PRE-CHECK GitLab Runner exists
  block:
  - name: (MacOS) Check gitlab-runner executable exists
    stat:
      path: "{{ gitlab_runner_executable }}"
    register: gitlab_runner_exists

  - name: (MacOS) Set fact -> gitlab_runner_exists
    set_fact:
      gitlab_runner_exists: "{{ gitlab_runner_exists.stat.exists }}"

- name: (MacOS) INSTALL GitLab Runner for macOS
  block:
    - name: (MacOS) Download GitLab Runner
      get_url:
        url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-darwin-amd64
        dest: "{{ gitlab_runner_executable }}"
        validate_certs: no

    - name: (MacOS) Setting Permissions for gitlab-runner executable
      file:
        path: "{{ gitlab_runner_executable }}"
        owner: "{{ ansible_user_id | string }}"
        group: "{{ ansible_user_gid | string }}"
        mode: '+x'

    - name: (MacOS) Install GitLab Runner
      command: "{{ gitlab_runner_executable }} install"

    - name: (MacOS) Start GitLab Runner
      command: "{{ gitlab_runner_executable }} start"

  when: (not gitlab_runner_exists)

- name: (MacOS) UPGRADE GitLab Runner for macOS
  block:
    - name: (MacOS) Stop GitLab Runner
      command: "{{ gitlab_runner_executable }} stop"

    - name: (MacOS) Download GitLab Runner
      get_url:
        url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-darwin-amd64
        dest: "{{ gitlab_runner_executable }}"
        validate_certs: no

    - name: (MacOS) Setting Permissions for gitlab-runner executable
      file:
        path: "{{ gitlab_runner_executable }}"
        owner: "{{ ansible_user_id | string }}"
        group: "{{ ansible_user_gid | string }}"
        mode: '+x'
      become: yes

    - name: (MacOS) Start GitLab Runner
      command: "{{ gitlab_runner_executable }} start"
  when: gitlab_runner_exists