---

- name: (RedHat) Get Gitlab repository installation script
  get_url:
    url: "https://packages.gitlab.com/install/repositories/runner/{{ gitlab_runner_package_name }}/script.rpm.sh"
    dest: /tmp/gitlab-runner.script.rpm.sh
    mode: 0744
  when: gitlab_runner_skip_package_repo_install is not defined or not gitlab_runner_skip_package_repo_install

- name: (RedHat) Install Gitlab repository
  shell: >
    os=el dist={{ '7' if ansible_distribution_major_version | int == 8 else ansible_distribution_major_version }}
    bash /tmp/gitlab-runner.script.rpm.sh
  args:
    creates: "/etc/yum.repos.d/runner_{{ gitlab_runner_package_name }}.repo"
  become: true
  when: gitlab_runner_skip_package_repo_install is not defined or not gitlab_runner_skip_package_repo_install

- name: (RedHat) Update gitlab_runner_package_name
  set_fact:
    gitlab_runner_package: "{{ gitlab_runner_package_name }}-{{ gitlab_runner_package_version }}"
    gitlab_runner_package_state: "present"
  when: gitlab_runner_package_version is defined

- name: (RedHat) Set gitlab_runner_package_name
  set_fact:
    gitlab_runner_package: "{{ gitlab_runner_package_name }}"
    gitlab_runner_package_state: "latest"
  when: gitlab_runner_package_version is not defined

- name: (RedHat) Install GitLab Runner
  package:
    name: "{{ gitlab_runner_package }}"
    state: "{{ gitlab_runner_package_state }}"
  become: true

- name: Ensure /etc/systemd/system/gitlab-runner.service.d/ exists
  file:
    path: /etc/systemd/system/gitlab-runner.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Add reload command to GitLab Runner system service
  copy:
    dest: /etc/systemd/system/gitlab-runner.service.d/exec-reload.conf
    content: |
      [Service]
      ExecReload=/bin/kill -HUP $MAINPID
  register: gitlab_runner_exec_reload

# https://docs.gitlab.com/runner/configuration/init.html#overriding-systemd
- name: Configure graceful stop for GitLab Runner system service
  copy:
    dest: /etc/systemd/system/gitlab-runner.service.d/kill.conf
    content: |
      [Service]
      TimeoutStopSec={{ gitlab_runner_timeout_stop_seconds }}
      KillSignal=SIGQUIT
  when: gitlab_runner_timeout_stop_seconds > 0
  register: gitlab_runner_kill_timeout

- name: Force systemd to reread configs
  systemd:
    daemon_reload: yes
  when: gitlab_runner_exec_reload.changed or gitlab_runner_kill_timeout
