---
# non macOS
- name: restart_gitlab_runner
  service: name=gitlab-runner state=restarted
  become: yes
  when: ansible_os_family != 'Darwin'

# macOS
- name: restart_gitlab_runner_macos
  command: "{{ gitlab_runner_executable }} restart"
  become: yes
  when: ansible_os_family == 'Darwin'
